## Numpy

In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.8 MB 7.2 MB/s eta 0:00:02
   ---------- ----------------------------- 3.4/12.8 MB 15.9 MB/s eta 0:00:01
   ------------------ --------------------- 5.8/12.8 MB 11.0 MB/s eta 0:00:01
   ------------------------- -------------- 8.1/12.8 MB 12.3 MB/s eta 0:00:01
   ----------------------------------- ---- 11.3/12.8 MB 11.8 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 11.3 MB/s eta 0:00:00



[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import numpy as np

arr1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])

#print(type(arr1))

print(arr1.shape)

(2, 5)


In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
arr1 = np.array([1,2,3,4,5])

print(arr1.shape)

(5,)


In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

arr1+arr2

array([ 4,  6,  8, 10, 12])

In [18]:
np.sqrt(16)

np.float64(4.0)

In [20]:
np.sqrt(4)

np.float64(2.0)

In [19]:
np.square(4)

np.int64(16)

In [21]:
np.exp(arr1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [23]:
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [24]:
np.cos(arr1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [30]:
arr1 = np.array([[1,2,3,4,5],[4,5,6,7,8]])
arr2 = np.array([3,4,5,6,7])

arr1[0][0]

np.int64(1)

In [32]:
arr1 = np.array([[1,2,3,4,5],[4,5,6,7,8]])
arr2 = np.array([3,4,5,6,7])

arr1[0][3]

np.int64(4)

In [34]:
arr1 = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,0,66]])
arr2 = np.array([3,4,5,6,7])

arr1[2][4]

np.int64(66)

In [35]:
!pip install pandas

  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.0 MB 4.9 MB/s eta 0:00:03
   ---------------- ----------------------- 4.5/11.0 MB 12.8 MB/s eta 0:00:01
   ------------------ --------------------- 5.0/11.0 MB 8.4 MB/s eta 0:00:01
   --------------------- ------------------ 6.0/11.0 MB 7.5 MB/s eta 0:00:01
   --------------------------- ------------ 7.6/11.0 MB 7.2 MB/s eta 0:00:01
   --------------------------------- ------ 9.2/11.0 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 8.1 MB/s eta 0:00:00
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)



[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


## pandas - powerful library for data manipulation. widely used for data analytics

In [36]:
import pandas as pd

In [38]:
data = [1,2,3,4,5]
series =pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [39]:
dictionary = {"one":1, "two":2, "three":3 }

print(pd.Series(dictionary))

one      1
two      2
three    3
dtype: int64


In [46]:
data1 = {
    "name":["ramesh","babu","suresh","bala"],
    "age":[20,35,40,35],
    "VoteID":[0,1,3,5],
}

print(pd.DataFrame(data1))

     name  age  VoteID
0  ramesh   20       0
1    babu   35       1
2  suresh   40       3
3    bala   35       5


## Reading varoius source data using pandas

In [49]:
data2 = '[{"name":"inthu","email":"inthujanjan@gmail.com","Role":"AI MI Engineer"}]'

df1 = pd.read_json(data2)
print(df1)

    name                  email            Role
0  inthu  inthujanjan@gmail.com  AI MI Engineer


C:\Users\Nixsala\AppData\Local\Temp\ipykernel_3468\572170618.py:3: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df1 = pd.read_json(data2)


In [50]:
df1

name                  email            Role
0  inthu  inthujanjan@gmail.com  AI MI Engineer

In [60]:
!pip install openpyxl


[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [61]:
df2 = pd.read_excel("Cola.xlsx")
df2

Data provided by SimFin  \
0                        NaN   
1    Profit & Loss statement   
2                        NaN   
3                        NaN   
4                        NaN   
..                       ...   
98                       NaN   
99                       NaN   
100                      NaN   
101                      NaN   
102                      NaN   

                                            Unnamed: 1 Unnamed: 2 Unnamed: 3  \
0                                                  NaN        NaN        NaN   
1                                                  NaN        NaN        NaN   
2                                       in million USD     FY '09     FY '10   
3                               NET OPERATING REVENUES      30990      35119   
4                                   Cost of goods sold      11088      12693   
..                                                 ...        ...        ...   
98   Effect of exchange rate changes on cash and ca...        576       -166   
99   Cash Provided by (Used in) Investing Activitie...        NaN        NaN   
100  Cash Provided by (Used in) Financing Activitie...        NaN        NaN   
101  Net Cash Provided by (Used in) Discontinued Op...        NaN        NaN   
102            Net increase (decrease) during the year       2320       1496   

    Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  \
0          NaN        NaN        NaN        NaN        NaN        NaN   
1          NaN        NaN        NaN        NaN        NaN        NaN   
2       FY '11     FY '12     FY '13     FY '14     FY '15     FY '16   
3        46542      48017      46854      45998      44294      41863   
4        18215      19053      18421      17889      17482      16465   
..         ...        ...        ...        ...        ...        ...   
98        -430       -255       -611       -934       -878         -6   
99         NaN        NaN        NaN        NaN          0          0   
100        NaN        NaN        NaN        NaN          0          0   
101        NaN        NaN        NaN        NaN          0          0   
102       4286      -4361       1972      -1456      -1649       1246   

    Unnamed: 10 Unnamed: 11  
0           NaN         NaN  
1           NaN         NaN  
2        FY '17      FY '18  
3         35410       31856  
4         13255       11770  
..          ...         ...  
98          241        -262  
99          -58        -421  
100         -38         205  
101          15          91  
102       -2477        2945  

[103 rows x 12 columns]

In [63]:
df1.to_pickle("df_pickle")

In [64]:
df4 = pd.read_pickle("df_pickle")

In [ ]:
df4

name                  email            Role
0  inthu  inthujanjan@gmail.com  AI MI Engineer

In [68]:
!pip install lxml


[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [71]:
!pip install html5lib


[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [75]:
!pip install beautifulsoup4


[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [31]:
# Step 1: Import pandas
import pandas as pd

# Step 2: Read the HTML file
df_list = pd.read_html("mi_sample.html")  # Returns a list

# Step 3: Extract the first table
#df5 = df_list[0]

# Step 4: Display it
df5

Name  Age         City
0   John   25     New York
1  Alice   30  Los Angeles
2    Bob   35      Chicago

In [32]:
somthing = pd.read_csv("Qwen.csv")

In [33]:
somthing

ID     Name  Age   Department  Salary         City
0   1    Alice   28  Engineering   70000     New York
1   2      Bob   34    Marketing   54000  Los Angeles
2   3  Charlie   29  Engineering   80000     New York
3   4    Diana   35           HR   60000      Chicago
4   5      Eve   30        Sales   58000      Seattle

In [3]:
import sqlite3
import pandas as pd

# Connect to the SQLite database file
conn = sqlite3.connect("school_database.sqlite")

# Read the school table
school_df = pd.read_sql("SELECT * FROM school", conn)

# Read the teacher table
teacher_df = pd.read_sql("SELECT * FROM teacher", conn)

# Display the data
print("School Table:")
print(school_df)

print("\nTeacher Table:")
print(teacher_df)

# Close the connection
conn.close()

School Table:
   school_id               name location
0          1  Green Valley High   Jaffna
1          2  Blue Star Academy  Colombo

Teacher Table:
   teacher_id        name      subject  school_id
0           1  Mr. Selvan  Mathematics          1
1           2   Ms. Priya      Science          2
2           3   Mr. Kumar      English          1


## Data Manipulation with Pandas

In [4]:
df = pd.read_csv("Online_Sale_Data.csv")
df.head()

OrderID        Date      Time     Category                      Product  \
0     1003  2025-03-01  16:45:08        Books  Web Development with Django   
1     1004  2025-03-02  09:12:33  Electronics             Wireless Earbuds   
2     1005  2025-03-02  11:30:15     Clothing              Smartwatch Band   
3     1006  2025-03-03  13:20:44        Books   Data Science for Beginners   
4     1007  2025-03-03  14:55:21  Electronics             Portable Charger   

   Quantity  UnitPrice  TotalPrice CustomerRegion PaymentMethod  \
0         1      44.99       44.99        Central    Debit Card   
1         2      79.99      159.98          South        PayPal   
2         1      29.99       29.99          North   Credit Card   
3         1      54.99       54.99           East     Gift Card   
4         1      39.99       39.99           West        PayPal   

   SatisfactionRating  
0                   5  
1                   4  
2                   3  
3                   5  
4                   4

In [5]:
df.tail()

OrderID        Date      Time     Category                 Product  \
5     1008  2025-03-04  10:08:11     Clothing      Programmer T-Shirt   
6     1009  2025-03-04  12:15:30  Electronics       Smart Home Camera   
7     1010  2025-03-05  08:44:17        Books  Machine Learning Guide   
8     1011  2025-03-05  17:33:59     Clothing   Hoodie - Tech Edition   
9     1012  2025-03-06  19:20:01  Electronics       Bluetooth Speaker   

   Quantity  UnitPrice  TotalPrice CustomerRegion PaymentMethod  \
5         2      24.99       49.98        Central   Credit Card   
6         1     129.99      129.99          South    Debit Card   
7         1      69.99       69.99          North        PayPal   
8         1      59.99       59.99           West     Gift Card   
9         1      89.99       89.99           East   Credit Card   

   SatisfactionRating  
5                   5  
6                   4  
7                   5  
8                   4  
9                   3

In [9]:
df.tail(9)

OrderID        Date      Time     Category                     Product  \
1     1004  2025-03-02  09:12:33  Electronics            Wireless Earbuds   
2     1005  2025-03-02  11:30:15     Clothing             Smartwatch Band   
3     1006  2025-03-03  13:20:44        Books  Data Science for Beginners   
4     1007  2025-03-03  14:55:21  Electronics            Portable Charger   
5     1008  2025-03-04  10:08:11     Clothing          Programmer T-Shirt   
6     1009  2025-03-04  12:15:30  Electronics           Smart Home Camera   
7     1010  2025-03-05  08:44:17        Books      Machine Learning Guide   
8     1011  2025-03-05  17:33:59     Clothing       Hoodie - Tech Edition   
9     1012  2025-03-06  19:20:01  Electronics           Bluetooth Speaker   

   Quantity  UnitPrice  TotalPrice CustomerRegion PaymentMethod  \
1         2      79.99      159.98          South        PayPal   
2         1      29.99       29.99          North   Credit Card   
3         1      54.99       54.99           East     Gift Card   
4         1      39.99       39.99           West        PayPal   
5         2      24.99       49.98        Central   Credit Card   
6         1     129.99      129.99          South    Debit Card   
7         1      69.99       69.99          North        PayPal   
8         1      59.99       59.99           West     Gift Card   
9         1      89.99       89.99           East   Credit Card   

   SatisfactionRating  
1                   4  
2                   3  
3                   5  
4                   4  
5                   5  
6                   4  
7                   5  
8                   4  
9                   3

In [7]:
df.head(9)

OrderID        Date      Time     Category                      Product  \
0     1003  2025-03-01  16:45:08        Books  Web Development with Django   
1     1004  2025-03-02  09:12:33  Electronics             Wireless Earbuds   
2     1005  2025-03-02  11:30:15     Clothing              Smartwatch Band   
3     1006  2025-03-03  13:20:44        Books   Data Science for Beginners   
4     1007  2025-03-03  14:55:21  Electronics             Portable Charger   
5     1008  2025-03-04  10:08:11     Clothing           Programmer T-Shirt   
6     1009  2025-03-04  12:15:30  Electronics            Smart Home Camera   
7     1010  2025-03-05  08:44:17        Books       Machine Learning Guide   
8     1011  2025-03-05  17:33:59     Clothing        Hoodie - Tech Edition   

   Quantity  UnitPrice  TotalPrice CustomerRegion PaymentMethod  \
0         1      44.99       44.99        Central    Debit Card   
1         2      79.99      159.98          South        PayPal   
2         1      29.99       29.99          North   Credit Card   
3         1      54.99       54.99           East     Gift Card   
4         1      39.99       39.99           West        PayPal   
5         2      24.99       49.98        Central   Credit Card   
6         1     129.99      129.99          South    Debit Card   
7         1      69.99       69.99          North        PayPal   
8         1      59.99       59.99           West     Gift Card   

   SatisfactionRating  
0                   5  
1                   4  
2                   3  
3                   5  
4                   4  
5                   5  
6                   4  
7                   5  
8                   4

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   OrderID             10 non-null     int64  
 1   Date                10 non-null     object 
 2   Time                10 non-null     object 
 3   Category            10 non-null     object 
 4   Product             10 non-null     object 
 5   Quantity            10 non-null     int64  
 6   UnitPrice           10 non-null     float64
 7   TotalPrice          10 non-null     float64
 8   CustomerRegion      10 non-null     object 
 9   PaymentMethod       10 non-null     object 
 10  SatisfactionRating  10 non-null     int64  
dtypes: float64(2), int64(3), object(6)
memory usage: 1012.0+ bytes


In [13]:
df.describe()

OrderID   Quantity   UnitPrice  TotalPrice  SatisfactionRating
count    10.00000  10.000000   10.000000   10.000000           10.000000
mean   1007.50000   1.200000   62.490000   72.988000            4.200000
std       3.02765   0.421637   31.644729   41.977137            0.788811
min    1003.00000   1.000000   24.990000   29.990000            3.000000
25%    1005.25000   1.000000   41.240000   46.237500            4.000000
50%    1007.50000   1.000000   57.490000   57.490000            4.000000
75%    1009.75000   1.000000   77.490000   84.990000            5.000000
max    1012.00000   2.000000  129.990000  159.980000            5.000000

In [15]:
df.isnull()

OrderID   Date   Time  Category  Product  Quantity  UnitPrice  TotalPrice  \
0    False  False  False     False    False     False      False       False   
1    False  False  False     False    False     False      False       False   
2    False  False  False     False    False     False      False       False   
3    False  False  False     False    False     False      False       False   
4    False  False  False     False    False     False      False       False   
5    False  False  False     False    False     False      False       False   
6    False  False  False     False    False     False      False       False   
7    False  False  False     False    False     False      False       False   
8    False  False  False     False    False     False      False       False   
9    False  False  False     False    False     False      False       False   

   CustomerRegion  PaymentMethod  SatisfactionRating  
0           False          False               False  
1           False          False               False  
2           False          False               False  
3           False          False               False  
4           False          False               False  
5           False          False               False  
6           False          False               False  
7           False          False               False  
8           False          False               False  
9           False          False               False

In [16]:
df.isnull().sum()

OrderID               0
Date                  0
Time                  0
Category              0
Product               0
Quantity              0
UnitPrice             0
TotalPrice            0
CustomerRegion        0
PaymentMethod         0
SatisfactionRating    0
dtype: int64

In [ ]:
#df.fillna(8)

In [19]:
df.dtypes

OrderID                 int64
Date                   object
Time                   object
Category               object
Product                object
Quantity                int64
UnitPrice             float64
TotalPrice            float64
CustomerRegion         object
PaymentMethod          object
SatisfactionRating      int64
dtype: object

In [20]:
df.rename(columns={"SatisfactionRating":"Rating"})

OrderID        Date      Time     Category                      Product  \
0     1003  2025-03-01  16:45:08        Books  Web Development with Django   
1     1004  2025-03-02  09:12:33  Electronics             Wireless Earbuds   
2     1005  2025-03-02  11:30:15     Clothing              Smartwatch Band   
3     1006  2025-03-03  13:20:44        Books   Data Science for Beginners   
4     1007  2025-03-03  14:55:21  Electronics             Portable Charger   
5     1008  2025-03-04  10:08:11     Clothing           Programmer T-Shirt   
6     1009  2025-03-04  12:15:30  Electronics            Smart Home Camera   
7     1010  2025-03-05  08:44:17        Books       Machine Learning Guide   
8     1011  2025-03-05  17:33:59     Clothing        Hoodie - Tech Edition   
9     1012  2025-03-06  19:20:01  Electronics            Bluetooth Speaker   

   Quantity  UnitPrice  TotalPrice CustomerRegion PaymentMethod  Rating  
0         1      44.99       44.99        Central    Debit Card       5  
1         2      79.99      159.98          South        PayPal       4  
2         1      29.99       29.99          North   Credit Card       3  
3         1      54.99       54.99           East     Gift Card       5  
4         1      39.99       39.99           West        PayPal       4  
5         2      24.99       49.98        Central   Credit Card       5  
6         1     129.99      129.99          South    Debit Card       4  
7         1      69.99       69.99          North        PayPal       5  
8         1      59.99       59.99           West     Gift Card       4  
9         1      89.99       89.99           East   Credit Card       3

In [29]:
df['DoubledRevenue'] = df['TotalPrice'].apply(lambda x: x * 2)

In [36]:
df['DoubledRevenue']

0     89.98
1    319.96
2     59.98
3    109.98
4     79.98
5     99.96
6    259.98
7    139.98
8    119.98
9    179.98
Name: DoubledRevenue, dtype: float64

In [37]:
df['Time'].unique()

array(['16:45:08', '09:12:33', '11:30:15', '13:20:44', '14:55:21',
       '10:08:11', '12:15:30', '08:44:17', '17:33:59', '19:20:01'],
      dtype=object)

In [38]:
df['Category'].unique()

array(['Books', 'Electronics', 'Clothing'], dtype=object)

In [40]:
mean_Price = df["mean_data"] = df.groupby('Category')['TotalPrice'].mean()

In [41]:
mean_Price

Category
Books           56.656667
Clothing        46.653333
Electronics    104.987500
Name: TotalPrice, dtype: float64